- name: play        
  hosts: alpine-example-com         
  tasks:                   
   - name: download file         
     uri:                  
       # url: https://api.github.com/         
       url: http://kubernetes.tn         
       return_content: true          
     register: downloaded_file         
   - name: print last task output         
     debug:                          
       var: downloaded_file.content         
